services:
  api:
    build: .
    container_name: scraper_api
    volumes:
      - ./user_data:/app/user_data
    restart: always
    ports:
      - "8000:8000"

  ngrok:
    image: ngrok/ngrok:latest
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=abdicable-dimple-inexplicit.ngrok-free.dev" # Domínio reservado
      - "api:8000"
    depends_on:
      - api
